### ISSUE TITLE
Colour changes cannot be nested

### ISSUE THREAD

**Issue by prantlf** [sindresorhus/yoctocolors#17]
If a colour is changed only for a substring, the rest of the main string won't continue in its previously selected colour. It appears that a call to `yoctocolors.colour()` doesn't revert just the colour change, which the method performed, but removes the previously selected colours as well.

For example, the string `" to use time limit"` won't be rendered red, but black (the default terminal colour):

```js
yoctocolors.red(" Add plugin " +  yoctocolors.yellow("name") + " to use time limit")
```

Screenshot:

![obrazek](https://github.com/sindresorhus/yoctocolors/assets/733193/0ba059b1-2da5-4e1a-ac7b-dccdb32103f3)

Code:

```js
import picocolors from "picocolors"
import * as yoctocolors from "yoctocolors"

let out

out =
  picocolors.bgRed(picocolors.black(" ERROR ")) +
  picocolors.red(
    " Add plugin " +
      picocolors.yellow("name") +
      " to use time limit"
  )
console.log(out)

out =
  yoctocolors.bgRed(yoctocolors.black(" ERROR ")) +
  yoctocolors.red(
    " Add plugin " +
      picocolors.yellow("name") +
      " to use time limit"
  )
console.log(out)
```

Setting and unsetting the bold flag (by calling `bold` instead of `yellow`) works well - the originally set colour is retained:

![obrazek](https://github.com/sindresorhus/yoctocolors/assets/733193/1783ebc3-ebc6-4171-83a6-ded8a7aac74d)

Similarly, setting and unsetting the background colour (by calling `bgYellow` instead of `yellow`) works well - the originally set text colour is retained:

![obrazek](https://github.com/sindresorhus/yoctocolors/assets/733193/9481c917-5144-443b-b25d-eb52d9f55b7b)

**Comment by sindresorhus** [comment]
Fixed in 2.0.1
