### ISSUE TITLE
`picocolors` has overtaken this package in smallness :)

### ISSUE THREAD

**Issue by illright** [sindresorhus/yoctocolors#22]
The package description describes `yoctocolors` as the smallest command-line coloring package on the internet, however, it seems like this is no longer the case, with `picocolors` being in the lead

https://pkg-size.dev/picocolors
<details><summary>Screenshot</summary><img width="1044" alt="image" src="https://github.com/user-attachments/assets/910684b4-3099-4acd-965a-fb819222cc5e" /></details>

https://pkg-size.dev/yoctocolors
<details><summary>Screenshot</summary><img width="1072" alt="image" src="https://github.com/user-attachments/assets/25f7d63f-56bf-4c90-8cac-e28c5d25a6f5" /></details>

Not that it requires any action on your side, but perhaps it means that there are more space savings to get. Not trying to shoot this package down either, I love your work :D

**Comment by sindresorhus** [comment]
Of course, it could always be smaller, but this is the smallest without affecting usability (like minifying or removing types/docs).
